id: A6988F6C9
title: f256D
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 20:25:50.366441
  last_modified_at: 2022-05-27 20:25:50.366449
